name: hisab
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter

  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  http: ^0.13.5
  google_fonts: ^3.0.1
  # flutter_screenutil: ^5.6.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  flutter_switch: ^0.3.2
  flutter_otp_text_field: ^1.1.1
  otp_text_field: ^1.1.3
  flutter_launcher_icons: ^0.13.1
  riverpod: ^2.3.7
  flutter_riverpod: ^2.3.7
  go_router: ^14.7.1
  # flutter_gen: ^5.11.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.14

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 19 # android min sdk min:16, default 21

# The following section is specific to Flutter packages.
flutter:

  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
        - asset: assets/fonts/Satoshi-BlackItalic.ttf
        - asset: assets/fonts/Satoshi-Bold.ttf
        - asset: assets/fonts/Satoshi-BoldItalic.ttf
        - asset: assets/fonts/Satoshi-Italic.ttf
        - asset: assets/fonts/Satoshi-Light.ttf
        - asset: assets/fonts/Satoshi-LightItalic.ttf
        - asset: assets/fonts/Satoshi-Medium.ttf
        - asset: assets/fonts/Satoshi-MediumItalic.ttf
        - asset: assets/fonts/Satoshi-Regular.ttf
